### PR TITLE
Add election results for lists, not just candidates

### PR DESCRIPTION
**Pull request by piemonkey**
### Overview
The model for this is very basic and is basically a hack to get this stuff to work. The results themselves come from extracting the relevant parts from a csv of the raw election results and processing them into a ttl. The only way to validate that the results are the expected ones is by matching multiple strings as we have no identifiers to compare to.

Draft as I'm unsure about the data and it needs a frontend release.

##### connected issues and PRs:
Jira ticket: https://binnenland.atlassian.net/browse/GN-5315
Corrects: https://github.com/lblod/frontend-gelinkt-notuleren/pull/784
Frontend PR: https://github.com/lblod/frontend-gelinkt-notuleren/pull/790.

### Setup
Needs to be tested with a version of the frontend that uses the data.

### How to test/reproduce
In the frontend, check that syncronisation works and produces the correct ordering based on fracties.

### Challenges/uncertainties
Why do we not have this data in a linked format?!?

### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [x ] changelog
- [ ] no new deprecations

### CODE REVIEW

**Comment by abeforgit** [comment]
ok fair, but still I feel its a lot of data we don't need? like all the names and such

**Comment by abeforgit** [comment]
we could also keep it in a separate graph to make sure we know where it's coming from

**Comment by piemonkey** [comment]
I suppose I could remove the extra data. I included as I was worried that I'd need to do more to validate that I've got the correct result. I guess we should add back in if it turns out to be needed.

**Comment by abeforgit** [comment]
still lots of duplicates:
```

<http://example.com/kieslijst-result/10000> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10001> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10002> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10003> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10004> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10005> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10006> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10007> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10008> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .

<http://example.com/kieslijst-result/10009> a ext:KieslijstResult ;
    ext:kieskring "Grimbergen" ;
    ext:lijst "SamenGrootGrimbergen" ;
    ext:stemcijfer 1856 .
```

**Comment by elpoelma** [comment]
I indeed understand not wanting to store this as linked data, as it is created by matching the names of the municipalities and candidate-lists. Of course, this is also (kind of) the way LMB must have converted it too linked-data, so... 
Whether we link it or not, based on this data a lot of legal documents are created anyway, so I don't really see why we shouldn't link it.
Additionally, I would indeed also link these results only the the candidate-list names and muncipality names, and not the candidates themselves.

**Comment by abeforgit** [comment]
suggestion: if you preprocess the excel to have only one row per result we need,
and then after inserting run something like:
```
SELECT count(distinct ?result) WHERE{
?unit a besluit:Bestuurseenheid.
?unit skos:prefLabel ?unitName.
?fraction org:linkedTo ?unit.
?fraction ext:geproduceerdDoor ?candidateList.
?candidateList skos:prefLabel ?listName

?result a ext:Kieslijstresult.
?result ext:kieskring ?unitName.
?result ext:lijst ?listName.

}
```
you should then get the same count as the amount of rows in the excel I think

**Comment by piemonkey** [comment]
> still lots of duplicates:
> 

Fixed.

**Review by elpoelma — COMMENTED** [review]
I think these migrations will work as expected. Just some side notes:
- We seem to be targetting fracties/kandidatenlijsten in general here, and not for a specific legislative period. This should however (in practice) not be a problem, as fractions/kandidatenlijsten of previous periods do not have the `ext:geproduceerdDoor` link, so we only target the next period anyway.

**Pull request merged**
