### PR TITLE
Feature/updated consumer

### PR DESCRIPTION
**Pull request by cecemel**
This PR updates the stack to use the updated consumer-flow.

### CODE REVIEW

**Review by nvdk — COMMENTED** [review]
Ran in to some oddities, but in general seemed to work:
- modified date of the task is not updated correctly
- looks like the initial sync somehow fetched an older file for the initial sync

**Comment by cecemel** [comment]
>     * looks like the initial sync somehow fetched an older file for the initial sync

Will look into this

**Comment by cecemel** [comment]
> We have some extra information in GN (which mandates should be considered part of the quorum for a specific bestuursorgaanclassificatie) which I fear might be cleared by this PR. needs further investigation.
Not sure what quorum means.

**Comment by nvdk** [comment]
> > We have some extra information in GN (which mandates should be considered part of the quorum for a specific bestuursorgaanclassificatie) which I fear might be cleared by this PR. needs further investigation.
> Not sure what quorum means.
Quorum is the actual voting body of the administrative body. E.g for the "gemeenteraden" only the "gemeenteraadsleden" can vote, but not the chairman even though that mandate is also linked to the administrative body. It looks like this was still working, during my brief testing.

**Comment by cecemel** [comment]
> > > We have some extra information in GN (which mandates should be considered part of the quorum for a specific bestuursorgaanclassificatie) which I fear might be cleared by this PR. needs further investigation.
> > > Not sure what quorum means.
> 
> Quorum is the actual voting body of the administrative body. E.g for the "gemeenteraden" only the "gemeenteraadsleden" can vote, but not the chairman even though that mandate is also linked to the administrative body. It looks like this was still working, during my brief testing.

If there is no conflict of the model, I don't expect issues. 

The tester has some extreme scenarios that's worth testing here too. (probably you have to fine tune the expected results for the specific business rules)
Typical scenarios where it previously would fail; Removal (i.e. archive) of mandatarissen and dealing with CRUD of hasMany relations.

**Comment by nvdk** [comment]
> If there is no conflict of the model, I don't expect issues.
> 

define conflict though, we added the following information to determine the correct roles for each type of bestuursorgaan:
` (instanceOf BestuursOrgaanClassificatieCode) ext:hasDefaultType (instanceOf BestuursfunctieCode)`

**Pull request closed without merging**
